# Generated by Django 4.2 on 2023-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='categoory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='picture',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
