# Generated by Django 4.2 on 2023-10-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_rename_categoory_picture_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
