# Generated by Django 4.2 on 2023-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kategori',
            field=models.CharField(default='article', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='judul',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
